package com.electricsheep.app.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable
import java.time.Instant

/**
 * Represents a mood entry with a numerical score and timestamp.
 * 
 * @param id Unique identifier (generated by repository if not provided)
 * @param userId ID of the user who created this mood entry
 * @param score Mood score (typically 1-10 or similar scale)
 * @param timestamp When the mood was recorded (Unix timestamp in milliseconds)
 * @param createdAt When the record was created in the system
 * @param updatedAt When the record was last updated
 */
@Entity(tableName = "moods")
@Serializable
data class Mood(
    @PrimaryKey
    val id: String,
    val userId: String,
    val score: Int,
    val timestamp: Long,
    val createdAt: Long? = null,
    val updatedAt: Long? = null
) {
    /**
     * Get the timestamp as an Instant for easier date handling
     */
    fun getTimestampInstant(): Instant = Instant.ofEpochMilli(timestamp)
    
    /**
     * Validate that the mood score is within acceptable range
     */
    fun isValid(): Boolean {
        return userId.isNotBlank() && score in 1..10 && timestamp > 0
    }
    
    /**
     * Create a copy with updated timestamp set to current time
     */
    fun withUpdatedTimestamp(): Mood {
        val now = System.currentTimeMillis()
        return copy(
            updatedAt = now,
            createdAt = createdAt ?: now
        )
    }
    
    /**
     * Check if this mood is newer than another based on updatedAt timestamp
     * Falls back to createdAt if updatedAt is null
     */
    fun isNewerThan(other: Mood): Boolean {
        val thisTimestamp = updatedAt ?: createdAt ?: 0L
        val otherTimestamp = other.updatedAt ?: other.createdAt ?: 0L
        return thisTimestamp > otherTimestamp
    }
}

